version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.2.1

executors:
  base:
    docker:
      - image: cimg/node:18.12.0
    environment:
      # Browsers are not needed outside of e2e tests
      PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1

workflows:
  main:
    jobs:
      - aws-ecr/build-and-push-image:
          name: build-image
          executor: base
          remote-docker-layer-caching: true
          setup-remote-docker: true
          dockerfile: Dockerfile
          repo: kelvintaywl/dlc-node
          extra-build-args: '--build-arg VERSION=${CIRCLE_SHA1}'
          tag: '${CIRCLE_SHA1}'
          push-image: false
          post-steps:
            - run: docker image ls
